### PR TITLE
Restore warning icons

### PR DESCRIPTION
**Pull request by jamonation**
So I think this sort of works to do what you're after, take a look at the changes here:
https://github.com/jamonation/dxr/commit/786d4fdeb1aae38304b8e9e4d54a00b592651dbd

The other stuff is just code highlighter changes, so ignore those (or pull from mozilla/dxr master).

Any thoughts about how to use the annotation icons? I've set it up so if there is more than one icon per line, on hover the rest will be displayed.

You have to click to display the warning which is a bit of a pain. But then using hover instead makes it hard to be able to select the actual annotation text since when you go to select it the warning disappears.

Is keeping the text visible so that you can copy/paste the note a useful thing?

### CODE REVIEW

**Comment by jamonation** [comment]
Think you could take a look at this @abbeyj ? I updated it to use latest master and it works with Omniglot & HG. It will break with Omniglot and git a little bit depending on the remote, but my changes to permalinks over in https://github.com/jamonation/dxr/commit/46658fc429caacaa8991899077d3d847ab0ce447 work with it as well. So when this commit and that are merged together icons should work perfectly with Omniglot enabled. cc @erikrose

**Comment by abbeyj** [comment]
I finally got a chance to look at this.  How do you get the text of the warning for annotations beyond the first?  I tried hovering and clicking and neither seems to work for me.

**Comment by jamonation** [comment]
So here it is @abbeyj - try making multiple icons show up on a line and then mouseover each one. The pop up text will change, and clicking the icon will make the pop up persist. All in https://github.com/jamonation/dxr/commit/d84ba50debb5dc7fba62304b7a00cb06aa05aa67 - ignore the older one.

**Comment by abbeyj** [comment]
Looking better now.  There's a problem with copy-and-paste.  When you select some code and copy and paste it into a text editor, each line gets 12 spaces at the beginning.  There also seems to be some spaces after each line that you can see when selecting them.

**Comment by jamonation** [comment]
I think the latest be11a948f912f01e941bd0ccba8d5e10a22eb004 commit fixes the space issues. There were indented spaces in the jinja2 code inside the pre tags, which got rendered as literal spaces.

**Comment by abbeyj** [comment]
Sorry I've been letting this sit around for so long.  I've just tried the newest version on a small sample and the code is 15px too high (probably due to the line: top: -15px; /\* for some reason this is needed or the lines are offset */).  Perhaps this problem only kicks in on certain examples?  I'm testing on a very simple main that just returns 0.  Any ideas?

**Comment by erikrose** [comment]
We did recently merge a pretty substantial rethink of the code layout CSS and markup. Maybe things are saner now and this needs to be revised to match....

**Pull request closed without merging**
